# Generated by Django 4.0.5 on 2022-06-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='name', max_length=20)),
                ('lastname', models.CharField(blank=True, default='surname', max_length=20, verbose_name='surname')),
                ('address', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField()),
            ],
        ),
    ]
